/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lsilva' at '16/12/15 4:40 PM' with Gradle 2.6
 *
 * @author lsilva, @date 16/12/15 4:40 PM
 */
public class WarpPipe {
    public boolean someLibraryMethod() {
        return true;
    }
}
