import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lsilva' at '16/12/15 4:40 PM' with Gradle 2.6
 *
 * @author lsilva, @date 16/12/15 4:40 PM
 */
public class WarpPipeTest {
    @Test
    public void testSomeLibraryMethod() {
        WarpPipe classUnderTest = new WarpPipe();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
